/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package lk.styrox.pharma_care.main_components;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author thara
 */
public class GradiantPanel extends javax.swing.JPanel {

    /** Creates new form GradiantPanel */
    
    public GradiantPanel() {
        setOpaque(false);
    }

    public void changeRoundPanel(int round) {
        if (round > 0) {
            ROUNDED_CONER_SIZE = round;
            setOpaque(false);
            repaint();
        }
    }
    
    public void changeRoundPanel(Color color1, Color color2) {
        if (color1 != null && color2 != null) {
            this.color1 = color1;
            this.color2 = color2;
            repaint();
            setForeground(Color.WHITE);
        }
    }

    private int ROUNDED_CONER_SIZE = 10;
    private Color color1 = Color.WHITE;
    private Color color2 = Color.WHITE;

    @Override
    public void paint(Graphics g) {
        Graphics2D gd = (Graphics2D) g.create();
        
        gd.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        gd.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        gd.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        
//        gd.setColor(this.getBackground());
        
        GradientPaint gra = new GradientPaint(0, 0, color1, getWidth(), getHeight(), color2);
        gd.setPaint(gra);
        gd.fillRoundRect(0, 0, getWidth(), getHeight(), ROUNDED_CONER_SIZE, ROUNDED_CONER_SIZE);
        gd.dispose();
        super.paint(g); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
