/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lk.starfield.yasoja.panels;

import java.awt.Color;
import java.awt.Font;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import java.sql.*;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import lk.starfield.yasoja.connection.Mysql;
import lk.starfield.yasoja.dialogs.Class_Registration;
import lk.starfield.yasoja.logger.Logger;
import lk.starfield.yasoja.validation.Valid_Status;
import raven.toast.Notifications;

/**
 *
 * @author dnana
 */
public class Class_Management extends javax.swing.JPanel {

    HashMap<String, String> subjectMap = new HashMap<>();
    JFrame parentFrame;

    /**
     * Creates new form Class_Management
     */
    public Class_Management(JFrame parent) {
        initComponents();
        loadTable();
        loadSubjects();
        parentFrame = parent;
    }

    private void loadSubjects() {
        try {
            ResultSet resultSet = Mysql.search("SELECT * FROM `subject`");

            Vector v = new Vector();
            v.add("Select Subject");
            while (resultSet.next()) {
                v.add(resultSet.getString("name"));
                subjectMap.put(resultSet.getString("name"), resultSet.getString("id"));
            }
            DefaultComboBoxModel m = new DefaultComboBoxModel(v);
            jComboBox1.setModel(m);

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void loadTable() {

        JTableHeader tableHeader = jTable1.getTableHeader();
        Font headerFont = new Font("Microsoft JhengHei ", Font.BOLD, 16);
        Color THcolorBg = new Color(6, 52, 119);
        Color THcolotFont = new Color(255, 255, 255);
        tableHeader.setBackground(THcolorBg);
        tableHeader.setForeground(THcolotFont);
        tableHeader.setFont(headerFont);
        jTable1.setTableHeader(tableHeader);

        DefaultTableCellRenderer columnRenderer = new DefaultTableCellRenderer();
        columnRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for (int columnIndex = 0; columnIndex < model.getColumnCount(); columnIndex++) {
            jTable1.getColumnModel().getColumn(columnIndex).setCellRenderer(columnRenderer);
        }

        try {
            ResultSet rs = Mysql.search("SELECT * FROM `class`"
                    + "INNER JOIN `teacher` ON `class`.`teacher_id`= `teacher`.`id`"
                    + "INNER JOIN `status` ON `class`.`status_id`= `status`.`id`"
                    + "INNER JOIN `subject` ON `subject`.`id`= `teacher`.`subject_id` "
                    + "INNER JOIN `class_day` ON `class`.`class_day_id`= `class_day`.`id`"
                    + "  ORDER BY `class`.`id` ASC  ");

            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString("class.id"));
                v.add(rs.getString("day"));
                v.add(rs.getString("start_time") + "-" + rs.getString("end_time"));
                v.add(rs.getString("status.status"));
                v.add(rs.getString("subject.name"));
                v.add(rs.getString("fname") + "-" + rs.getString("lname"));
                model.addRow(v);
                jTable1.setModel(model);
            }

        } catch (Exception e) {
            Logger.log(String.valueOf(e));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new lk.starfield.yasoja.main_components.Background();
        background2 = new lk.starfield.yasoja.main_components.Background();
        background3 = new lk.starfield.yasoja.main_components.Background();
        roundButton1 = new lk.starfield.yasoja.main_components.roundButton();
        jLabel2 = new javax.swing.JLabel();
        roundButton2 = new lk.starfield.yasoja.main_components.roundButton();
        background4 = new lk.starfield.yasoja.main_components.Background();
        roundButton4 = new lk.starfield.yasoja.main_components.roundButton();
        jLabel4 = new javax.swing.JLabel();
        ID = new lk.starfield.yasoja.main_components.roundTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        background2.setBackground(new java.awt.Color(255, 255, 255));

        background3.setBackground(new java.awt.Color(231, 231, 233));

        roundButton1.setBackground(new java.awt.Color(232, 194, 255));
        roundButton1.setForeground(new java.awt.Color(104, 2, 166));
        roundButton1.setText("Update Student Details");
        roundButton1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        roundButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Leelawadee", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Processes");

        roundButton2.setBackground(new java.awt.Color(192, 218, 255));
        roundButton2.setForeground(new java.awt.Color(30, 0, 215));
        roundButton2.setText("Register Class");
        roundButton2.setFocusable(false);
        roundButton2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        roundButton2.setPreferredSize(new java.awt.Dimension(164, 30));
        roundButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout background3Layout = new javax.swing.GroupLayout(background3);
        background3.setLayout(background3Layout);
        background3Layout.setHorizontalGroup(
            background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(roundButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(roundButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        background3Layout.setVerticalGroup(
            background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        background4.setBackground(new java.awt.Color(231, 231, 233));

        roundButton4.setBackground(new java.awt.Color(165, 199, 249));
        roundButton4.setForeground(new java.awt.Color(6, 52, 119));
        roundButton4.setText("Search Class");
        roundButton4.setFocusable(false);
        roundButton4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        roundButton4.setPreferredSize(new java.awt.Dimension(164, 30));
        roundButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundButton4ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Class ID");

        ID.setBackground(new java.awt.Color(255, 255, 255));
        ID.setForeground(new java.awt.Color(51, 51, 51));
        ID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Student Name");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout background4Layout = new javax.swing.GroupLayout(background4);
        background4.setLayout(background4Layout);
        background4Layout.setHorizontalGroup(
            background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background4Layout.createSequentialGroup()
                .addGroup(background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(background4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(roundButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );
        background4Layout.setVerticalGroup(
            background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(roundButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Class ID", "Class Day/s", "Time Peroid", "Class Status", "Subject", "Teacher"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(120);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(120);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(140);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(140);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(170);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(190);
        }

        javax.swing.GroupLayout background2Layout = new javax.swing.GroupLayout(background2);
        background2.setLayout(background2Layout);
        background2Layout.setHorizontalGroup(
            background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(background3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(background2Layout.createSequentialGroup()
                        .addComponent(background4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        background2Layout.setVerticalGroup(
            background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(background3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(background4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void roundButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButton1ActionPerformed
//        String STno = ID.getText();
//        try {
//            ResultSet student = Mysql.search("SELECT * FROM `student`"
//                    + "INNER JOIN `batch` ON `student`.`batch_id`=`batch`.`id` WHERE `student`.`id`='" + STno + "'");
//            if (STno.isBlank()) {
//
//                Notifications.getInstance().show(Notifications.Type.WARNING,
//                        Notifications.Location.TOP_CENTER, "Please type Student No to search for student");
//            } else if (!student.next()) {
//                Notifications.getInstance().show(Notifications.Type.WARNING,
//                        Notifications.Location.TOP_CENTER, "Student ID does not match any reistered Data");
//            } else {
//                new Update_Students(parentFrame, STno, true).setVisible(true);
//                roundButton4ActionPerformed(evt);
//
//            }
//        } catch (Exception e) {
//            throw new RuntimeException(e);
//        }
    }//GEN-LAST:event_roundButton1ActionPerformed

    private void roundButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButton2ActionPerformed
        new Class_Registration(parentFrame, true).setVisible(true);
    }//GEN-LAST:event_roundButton2ActionPerformed

    private void roundButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButton4ActionPerformed
        String classID = ID.getText();
        String subject = String.valueOf(jComboBox1.getSelectedItem());

        String subjectID = subjectMap.get(subject);

        String query = "SELECT * FROM `class`"
                + "INNER JOIN `teacher` ON `class`.`teacher_id`= `teacher`.`id`"
                + "INNER JOIN `status` ON `class`.`status_id`= `status`.`id`"
                + "INNER JOIN `subject` ON `subject`.`id`= `teacher`.`subject_id` "
                + "INNER JOIN `class_day` ON `class`.`class_day_id`= `class_day`.`id`";

        if (classID.isBlank() && subject.equals("Select Subject")) {
            Notifications.getInstance().show(Notifications.Type.WARNING,
                    Notifications.Location.TOP_CENTER, "Please enter class ID or select subject");
            loadTable();
        } else if (!classID.isBlank() && subject.equals("Select Subject")) {
            query = query + " WHERE `class`.`id`='" + classID + "'";
        } else if (classID.isBlank() && !subject.equals("Select Subject")) {
            query = query + " WHERE `subject_id`='" + subjectID + "'";
        } else {
            loadTable();
        }

        try {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            ResultSet rs = Mysql.search(query);

            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString("class.id"));
                v.add(rs.getString("day"));
                v.add(rs.getString("start_time") + "-" + rs.getString("end_time"));
                v.add(rs.getString("status.status"));
                v.add(rs.getString("subject.name"));
                v.add(rs.getString("fname") + "-" + rs.getString("lname"));
                model.addRow(v);
                jTable1.setModel(model);
            }

        } catch (Exception e) {
            Logger.log(String.valueOf(e));
        }
    }//GEN-LAST:event_roundButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lk.starfield.yasoja.main_components.roundTextField ID;
    private lk.starfield.yasoja.main_components.Background background1;
    private lk.starfield.yasoja.main_components.Background background2;
    private lk.starfield.yasoja.main_components.Background background3;
    private lk.starfield.yasoja.main_components.Background background4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private lk.starfield.yasoja.main_components.roundButton roundButton1;
    private lk.starfield.yasoja.main_components.roundButton roundButton2;
    private lk.starfield.yasoja.main_components.roundButton roundButton4;
    // End of variables declaration//GEN-END:variables
}
