/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lk.starfield.yasoja.panels;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import raven.toast.Notifications;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import lk.starfield.yasoja.connection.Mysql;
import lk.starfield.yasoja.main_components.roundButton;
import lk.starfield.yasoja.main_components.roundTextField;
import lk.starfield.yasoja.validation.Valid_Status;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author dnana
 */
public class Payment extends javax.swing.JPanel {

    JFrame parentFrame;
    double total = 0;
    
    public Payment(JFrame parent) {
        initComponents();
        parentFrame = parent;
        Notifications.getInstance().setJFrame(parentFrame);
        loadTableHeader();
        totalLabel.setText(String.valueOf(total));
    }

    private void loadTableHeader() {

        JTableHeader tableHeader = jTable1.getTableHeader();
        Font headerFont = new Font("Microsoft JhengHei ", Font.BOLD, 16);
        Color THcolorBg = new Color(6, 52, 119);
        Color THcolotFont = new Color(255, 255, 255);
        tableHeader.setBackground(THcolorBg);
        tableHeader.setForeground(THcolotFont);
        tableHeader.setFont(headerFont);
        jTable1.setTableHeader(tableHeader);

        DefaultTableCellRenderer columnRenderer = new DefaultTableCellRenderer();
        columnRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        for (int columnIndex = 0; columnIndex < model.getColumnCount(); columnIndex++) {
            jTable1.getColumnModel().getColumn(columnIndex).setCellRenderer(columnRenderer);
        }
    }

    public roundTextField getID() {
        return ID;
    }

    public roundTextField getClassID() {
        return classID;
    }

    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new lk.starfield.yasoja.main_components.Background();
        background4 = new lk.starfield.yasoja.main_components.Background();
        roundButton5 = new lk.starfield.yasoja.main_components.roundButton();
        jLabel11 = new javax.swing.JLabel();
        classID = new lk.starfield.yasoja.main_components.roundTextField();
        jLabel5 = new javax.swing.JLabel();
        classFees = new lk.starfield.yasoja.main_components.roundTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        background3 = new lk.starfield.yasoja.main_components.Background();
        roundButton4 = new lk.starfield.yasoja.main_components.roundButton();
        jLabel4 = new javax.swing.JLabel();
        ID = new lk.starfield.yasoja.main_components.roundTextField();
        jLabel6 = new javax.swing.JLabel();
        Name = new lk.starfield.yasoja.main_components.roundTextField();
        jLabel7 = new javax.swing.JLabel();
        NIC = new lk.starfield.yasoja.main_components.roundTextField();
        jLabel9 = new javax.swing.JLabel();
        Batch = new lk.starfield.yasoja.main_components.roundTextField();
        jLabel10 = new javax.swing.JLabel();
        Email = new lk.starfield.yasoja.main_components.roundTextField();
        background5 = new lk.starfield.yasoja.main_components.Background();
        roundButton6 = new lk.starfield.yasoja.main_components.roundButton();
        jLabel12 = new javax.swing.JLabel();
        totalLabel = new lk.starfield.yasoja.main_components.roundTextField();

        background1.setBackground(new java.awt.Color(255, 255, 255));

        background4.setBackground(new java.awt.Color(231, 231, 233));

        roundButton5.setBackground(new java.awt.Color(194, 237, 255));
        roundButton5.setForeground(new java.awt.Color(9, 145, 204));
        roundButton5.setText("Add to Table");
        roundButton5.setFocusable(false);
        roundButton5.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        roundButton5.setPreferredSize(new java.awt.Dimension(164, 30));
        roundButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundButton5ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Class ID");

        classID.setBackground(new java.awt.Color(255, 255, 255));
        classID.setForeground(new java.awt.Color(51, 51, 51));
        classID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        classID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                classIDKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Class Fees");

        classFees.setEditable(false);
        classFees.setBackground(new java.awt.Color(255, 255, 255));
        classFees.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout background4Layout = new javax.swing.GroupLayout(background4);
        background4.setLayout(background4Layout);
        background4Layout.setHorizontalGroup(
            background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(classID, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(classFees, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(roundButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        background4Layout.setVerticalGroup(
            background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(classID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel5)
                        .addComponent(classFees, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(roundButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject", "Teacher Name", "Class ID", "Time Peroid", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(160);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(190);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(230);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(140);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(170);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(200);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(120);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(150);
        }

        background3.setBackground(new java.awt.Color(231, 231, 233));

        roundButton4.setBackground(new java.awt.Color(165, 199, 249));
        roundButton4.setForeground(new java.awt.Color(6, 52, 119));
        roundButton4.setText("Search Student");
        roundButton4.setFocusable(false);
        roundButton4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        roundButton4.setPreferredSize(new java.awt.Dimension(164, 30));
        roundButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundButton4ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Student ID");

        ID.setBackground(new java.awt.Color(255, 255, 255));
        ID.setForeground(new java.awt.Color(51, 51, 51));
        ID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Student Name");

        Name.setEditable(false);
        Name.setBackground(new java.awt.Color(255, 255, 255));
        Name.setForeground(new java.awt.Color(51, 51, 51));

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("NIC");

        NIC.setEditable(false);
        NIC.setBackground(new java.awt.Color(255, 255, 255));
        NIC.setForeground(new java.awt.Color(51, 51, 51));

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Batch");

        Batch.setEditable(false);
        Batch.setBackground(new java.awt.Color(255, 255, 255));
        Batch.setForeground(new java.awt.Color(51, 51, 51));

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Email");

        Email.setEditable(false);
        Email.setBackground(new java.awt.Color(255, 255, 255));
        Email.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout background3Layout = new javax.swing.GroupLayout(background3);
        background3.setLayout(background3Layout);
        background3Layout.setHorizontalGroup(
            background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(roundButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
            .addGroup(background3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addGroup(background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NIC, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Batch, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        background3Layout.setVerticalGroup(
            background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(roundButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(2, 2, 2)
                .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(2, 2, 2)
                .addComponent(Batch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NIC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        background5.setBackground(new java.awt.Color(231, 231, 233));

        roundButton6.setBackground(new java.awt.Color(196, 248, 241));
        roundButton6.setForeground(new java.awt.Color(31, 125, 112));
        roundButton6.setText("Print Invoice");
        roundButton6.setFocusable(false);
        roundButton6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        roundButton6.setPreferredSize(new java.awt.Dimension(164, 30));
        roundButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundButton6ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Total");

        totalLabel.setEditable(false);
        totalLabel.setBackground(new java.awt.Color(255, 255, 255));
        totalLabel.setForeground(new java.awt.Color(51, 51, 51));
        totalLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout background5Layout = new javax.swing.GroupLayout(background5);
        background5.setLayout(background5Layout);
        background5Layout.setHorizontalGroup(
            background5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(roundButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        background5Layout.setVerticalGroup(
            background5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(background5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roundButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(background4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addComponent(background3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
                            .addComponent(background5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(background4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(background5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(background3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void roundButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButton5ActionPerformed
        String STno = ID.getText();
        String Cno = classID.getText();

        try {
            ResultSet student = Mysql.search("SELECT * FROM `student` WHERE `id`='" + STno + "'");

            ResultSet class_rs = Mysql.search("SELECT * FROM `class`"
                    + " INNER JOIN `teacher` ON `class`.`teacher_id`=`teacher`.`id`"
                    + "INNER JOIN `subject` ON `teacher`.`subject_id`=`subject`.`id`"
                    + " WHERE `class`.`id`='" + Cno + "' ");

            if (STno.isBlank()) {
                Notifications.getInstance().show(Notifications.Type.WARNING,
                        Notifications.Location.TOP_CENTER, "Please select a batch");
            } else if (!student.next()) {
                Notifications.getInstance().show(Notifications.Type.WARNING,
                        Notifications.Location.TOP_CENTER, "Batch ID does not match any reistered Data");
            }
            if (Cno.isBlank()) {
                Notifications.getInstance().show(Notifications.Type.WARNING,
                        Notifications.Location.TOP_CENTER, "Please select a class");
            } else if (!class_rs.next()) {
                Notifications.getInstance().show(Notifications.Type.WARNING,
                        Notifications.Location.TOP_CENTER, "Class ID does not match any reistered Data");
            } else {

                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);

                Vector v = new Vector();
                v.add(class_rs.getString("subject.name"));
                v.add(class_rs.getString("teacher.fname") + " " + class_rs.getString("teacher.lname"));
                v.add(class_rs.getString("class.id"));
                v.add(class_rs.getString("start_time") + " " + class_rs.getString("end_time"));
                v.add(class_rs.getString("subject.fee"));

                model.addRow(v);
                jTable1.setModel(model);

                total = total + class_rs.getDouble("subject.fee");
                totalLabel.setText(String.valueOf(total));
                classID.setText("");
                classFees.setText("");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_roundButton5ActionPerformed

    private void roundButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButton4ActionPerformed
        String STno = ID.getText();

        if (STno.isBlank()) {
            Notifications.getInstance().show(Notifications.Type.WARNING,
                    Notifications.Location.TOP_CENTER, "Please type Student No to search for student");
        } else {
            try {
                ResultSet student_details = Mysql.search("SELECT * FROM `student`"
                        + "INNER JOIN `batch` ON `student`.`batch_id`=`batch`.`id` WHERE `student`.`id`='" + STno + "' ");

                if (student_details.next()) {
                    ResultSet student_class = Mysql.search("SELECT * FROM `student`"
                            + "INNER JOIN `batch` ON `student`.`batch_id`=`batch`.`id`"
                            + "WHERE `student`.`id` = '" + STno + "' ");

                    ID.setText(student_details.getString("student.id"));
                    Name.setText(student_details.getString("fname") + " " + student_details.getString("lname"));
                    Batch.setText(student_details.getString("batch.name"));
                    NIC.setText(student_details.getString("nic"));
                    Email.setText(student_details.getString("email"));

                } else {
                    Notifications.getInstance().show(Notifications.Type.WARNING,
                            Notifications.Location.TOP_CENTER, "Student ID does not match any reistered Data");
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_roundButton4ActionPerformed

    private void roundButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButton6ActionPerformed

        String STno = ID.getText();
        String name = Name.getText();
        String batch = Batch.getText();
        String nic = NIC.getText();
        String email = Email.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        String date = sdf.format(new java.util.Date());
        String invoice = String.valueOf(System.currentTimeMillis());

        int rowcount = jTable1.getRowCount();
        if (STno.isBlank() || name.isBlank() || batch.isBlank() || nic.isBlank() || email.isBlank()) {
            Notifications.getInstance().show(Notifications.Type.WARNING,
                    Notifications.Location.TOP_CENTER, "Please select a student");
        } else if (rowcount > 0) {

            try {
                HashMap<String, Object> parameters = new HashMap<>();
                parameters.put("invoice", invoice);
                parameters.put("date", date);
                parameters.put("name", name);
                parameters.put("batch", batch);
                parameters.put("nic", nic);
                parameters.put("email", email);
                parameters.put("total", String.valueOf(total));
                
                JasperReport compiledReport = JasperCompileManager.compileReport("src/lk/starfield/yasoja/reports/Starfield_invoice.jrxml");
                JRDataSource datasource = new JRTableModelDataSource(jTable1.getModel());
                JasperPrint report = JasperFillManager.fillReport(compiledReport, parameters, datasource);
                JasperViewer.viewReport(report,false);
                
                for (int x=0;x< rowcount;x++){
                    String Cno=String.valueOf(jTable1.getValueAt(x,2));
                    
                    Mysql.iud("UPDATE `class_enroll` SET `payment_status`='5' "
                            + "WHERE `student_ID`='"+STno+"' AND `class_id`='"+Cno+"' ");
                
                    Mysql.iud("INSERT INTO `invoice` VALUES ('"+invoice+"','"+date+"','"+Cno+"','"+STno+"') ");
                }
            } catch (Exception e) {

                e.printStackTrace();
            }
        } else {
            Notifications.getInstance().show(Notifications.Type.WARNING,
                    Notifications.Location.TOP_CENTER, "Please select and a class to the table");
        }
    }//GEN-LAST:event_roundButton6ActionPerformed

    private void classIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_classIDKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String class_id = classID.getText();

            try {
                ResultSet rs = Mysql.search("SELECT * FROM `class`"
                        + "INNER JOIN `teacher` ON `class`.`teacher_id`=`teacher`.`id`"
                        + "INNER JOIN `subject` ON `teacher`.`subject_id`=`subject`.`id`"
                        + " WHERE `class`.`id` = '" + class_id + "' ");

                if (rs.next()) {
                    classID.setText(rs.getString("class.id"));
                    classFees.setText(rs.getString("subject.fee"));
                } else {
                    classID.setText("");
                }
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        }
    }//GEN-LAST:event_classIDKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lk.starfield.yasoja.main_components.roundTextField Batch;
    private lk.starfield.yasoja.main_components.roundTextField Email;
    private lk.starfield.yasoja.main_components.roundTextField ID;
    private lk.starfield.yasoja.main_components.roundTextField NIC;
    private lk.starfield.yasoja.main_components.roundTextField Name;
    private lk.starfield.yasoja.main_components.Background background1;
    private lk.starfield.yasoja.main_components.Background background3;
    private lk.starfield.yasoja.main_components.Background background4;
    private lk.starfield.yasoja.main_components.Background background5;
    private lk.starfield.yasoja.main_components.roundTextField classFees;
    private lk.starfield.yasoja.main_components.roundTextField classID;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private lk.starfield.yasoja.main_components.roundButton roundButton4;
    private lk.starfield.yasoja.main_components.roundButton roundButton5;
    private lk.starfield.yasoja.main_components.roundButton roundButton6;
    private lk.starfield.yasoja.main_components.roundTextField totalLabel;
    // End of variables declaration//GEN-END:variables
}
